apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-example
policyDefaults:
  namespace: default
  placement:
    labelSelector:
      rhdp_usage: development
  remediationAction: inform
policies:
  - name: openshift-gitops-installed
    manifests:
      - path: openshift-gitops-subscription.yaml
  - name: kubeadmin-removed
    manifests:
      - path: kubeadmin-pass.yaml
    complianceType: mustnothave
    
